version: '3'

services:

    app:
      build: ./nodejs/
      container_name: node-app
      command: node index.js
      entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
      tty: true
      networks:
        - node-network
      volumes:
      - ./nodejs:/usr/src/app
      depends_on:
        - db

    db:
      image: mysql:5.7
        
      container_name: db
      restart: always
      tty: true
      environment:
        - MYSQL_DATABASE=nodedb
        - MYSQL_ROOT_PASSWORD=root
      networks:
        - node-network
      volumes:
      - ./mysql:/var/lib/mysql
    
    nginx:
      build: ./nginx/
      container_name: nginx-server
      restart: unless-stopped
      tty: true
      ports:
        - "8080:80"
      networks:
        - node-network
      depends_on:
        - app

networks:
  node-network:
    driver: bridge
